spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/authdb}
    username: ${DB_USER:auth}
    password: ${DB_PASSWORD:auth}
  jpa:
    show-sql: false

logging:
  level:
    org.springframework.security: INFO
