spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: false

security:
  jwt:
    issuer: ${JWT_ISSUER}
    audience: ${JWT_AUDIENCE}
    keys:
      public-key-location: ${JWT_PUBLIC_KEY_LOCATION}
      private-key-location: ${JWT_PRIVATE_KEY_LOCATION}

logging:
  level:
    root: INFO
    org.springframework.security: INFO
