import { useEffect, useState, useSyncExternalStore, type FormEvent, type ReactNode } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Activity, AlertTriangle, CheckCircle2, Clock3, Copy, Fingerprint, FlaskConical, KeyRound, Laptop, LogOut, RefreshCw, RotateCcwKey, Server, ShieldCheck, Smartphone, Trash2, UserRoundCheck } from 'lucide-react';
import { toast } from 'sonner';
import { Link, useNavigate } from 'react-router-dom';
import { activityStore } from '../lib/activity';
import { apiRequest, authApi, ApiError, API_BASE_URL } from '../lib/api';
import { useAuth } from '../lib/auth';
import type { ActivityEntry, AuthSession } from '../lib/types';
import { Button, Card, DangerButton, Field, PageHeader, ProblemPanel, SecondaryButton, Spinner, StatusPill, SuccessPanel, cn } from '../components/ui';

function useNow() { const [now, setNow] = useState(() => Date.now()); useEffect(() => { const id = window.setInterval(() => setNow(Date.now()), 1000); return () => window.clearInterval(id); }, []); return now; }
function secondsUntil(instant: string | undefined, now: number) { if (!instant) return 0; return Math.max(0, Math.floor((new Date(instant).getTime() - now) / 1000)); }
function duration(seconds: number) { if (seconds <= 0) return 'expirado'; const days = Math.floor(seconds / 86400); if (days) return `${days}d ${Math.floor((seconds % 86400) / 3600)}h`; const hours = Math.floor(seconds / 3600); if (hours) return `${hours}h ${Math.floor((seconds % 3600) / 60)}m`; const mins = Math.floor(seconds / 60); return `${mins}m ${seconds % 60}s`; }
function formatDate(value: string) { return new Intl.DateTimeFormat('es-MX', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value)); }
function sessionsQuery() { return { queryKey: ['sessions'], queryFn: authApi.sessions, staleTime: 5_000 } as const; }

export function DashboardPage() {
  const auth = useAuth(); const now = useNow(); const { data: sessions = [], isLoading, error, refetch, isFetching } = useQuery(sessionsQuery());
  const accessTtl = secondsUntil(auth.tokens?.accessTokenExpiresAt, now); const refreshTtl = secondsUntil(auth.tokens?.refreshTokenExpiresAt, now); const roles = Array.isArray(auth.jwt.claims?.roles) ? auth.jwt.claims.roles as unknown[] : [];
  return <div className="space-y-8"><PageHeader eyebrow="Authentication observability" title={<>Panel de <span className="gradient-text">seguridad</span></>} description="Estado vivo de la sesión, expiraciones y superficie autenticada del backend modular." action={<SecondaryButton onClick={() => refetch()} disabled={isFetching}>{isFetching ? <Spinner /> : <RefreshCw className="h-4 w-4" />} Actualizar</SecondaryButton>} /><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric icon={ShieldCheck} value={isLoading ? '…' : String(sessions.length)} label="Sesiones activas" detail="Devueltas por GET /sessions" tone="blue" /><Metric icon={Clock3} value={duration(accessTtl)} label="Access token" detail="JWT corto y stateless" tone="violet" /><Metric icon={RotateCcwKey} value={duration(refreshTtl)} label="Refresh token" detail="Rotatorio y persistido como hash" tone="emerald" /><Metric icon={UserRoundCheck} value={String(roles.length || 1)} label="Authorities" detail={roles.length ? roles.join(', ') : 'Claims disponibles en JWT'} tone="amber" /></div><ProblemPanel error={error} title="No se pudo leer la superficie autenticada" /><div className="grid gap-6 xl:grid-cols-[1.2fr_.8fr]"><Card className="p-5 sm:p-6"><div className="flex items-center justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-slate-400">Sesión actual</p><h2 className="font-display mt-2 text-xl font-bold">{auth.tokens?.sessionId}</h2></div><StatusPill tone="green">autenticado</StatusPill></div><dl className="mt-6 grid gap-4 sm:grid-cols-2"><Detail label="Subject" value={String(auth.jwt.claims?.sub || '—')} /><Detail label="Issuer" value={String(auth.jwt.claims?.iss || '—')} /><Detail label="Key ID" value={String(auth.jwt.header?.kid || '—')} /><Detail label="Token type" value={String(auth.jwt.claims?.token_type || '—')} /></dl><div className="mt-6 flex flex-wrap gap-3"><Link className="focus-ring inline-flex h-10 items-center rounded-lg bg-[#0055FF] px-4 text-sm font-semibold text-white" to="/app/sessions">Gestionar sesiones</Link><Link className="focus-ring inline-flex h-10 items-center rounded-lg border border-slate-200 px-4 text-sm font-semibold dark:border-slate-700" to="/app/tokens">Inspeccionar JWT</Link></div></Card><Card className="p-5 sm:p-6"><p className="text-xs font-bold uppercase tracking-[.16em] text-slate-400">Qué estás comprobando</p><div className="mt-4 space-y-4"><Checklist text="Bearer access token aceptado por Spring Security" /><Checklist text="Refresh token separado del access token" /><Checklist text="Sesión persistida y ownership por usuario" /><Checklist text="Claims issuer/audience/sid/token_type presentes" /></div></Card></div></div>;
}

function Metric({ icon: Icon, value, label, detail, tone }: { icon: typeof ShieldCheck; value: string; label: string; detail: string; tone: 'blue' | 'violet' | 'emerald' | 'amber' }) { const map = { blue: 'bg-blue-50 text-blue-600 dark:bg-blue-500/10 dark:text-blue-300', violet: 'bg-violet-50 text-violet-600 dark:bg-violet-500/10 dark:text-violet-300', emerald: 'bg-emerald-50 text-emerald-600 dark:bg-emerald-500/10 dark:text-emerald-300', amber: 'bg-amber-50 text-amber-600 dark:bg-amber-500/10 dark:text-amber-300' }; return <Card className="p-4 sm:p-5"><div className={cn('grid h-10 w-10 place-items-center rounded-xl', map[tone])}><Icon className="h-5 w-5" /></div><p className="font-display mt-5 truncate text-2xl font-bold sm:text-3xl">{value}</p><p className="mt-2 text-sm font-semibold">{label}</p><p className="mt-1 truncate text-xs text-slate-500 dark:text-slate-400">{detail}</p></Card>; }
function Detail({ label, value }: { label: string; value: string }) { return <div className="min-w-0 rounded-xl bg-slate-50 p-3 dark:bg-slate-900"><dt className="text-[10px] font-bold uppercase tracking-[.14em] text-slate-400">{label}</dt><dd className="mt-1 truncate font-mono text-xs" title={value}>{value}</dd></div>; }
function Checklist({ text }: { text: string }) { return <div className="flex gap-3"><span className="mt-0.5 grid h-5 w-5 shrink-0 place-items-center rounded-full bg-emerald-50 text-emerald-600 dark:bg-emerald-500/10"><CheckCircle2 className="h-3.5 w-3.5" /></span><p className="text-sm leading-6 text-slate-600 dark:text-slate-300">{text}</p></div>; }

export function SessionsPage() {
  const queryClient = useQueryClient(); const auth = useAuth(); const navigate = useNavigate(); const { data: sessions = [], isLoading, error, refetch, isFetching } = useQuery(sessionsQuery()); const [mutationError, setMutationError] = useState<unknown>(null);
  const revoke = useMutation({ mutationFn: authApi.revokeSession, onSuccess: (_, sessionId) => { setMutationError(null); queryClient.invalidateQueries({ queryKey: ['sessions'] }); toast.success('Sesión revocada'); if (sessionId === auth.tokens?.sessionId) { auth.clear(); navigate('/login', { replace: true }); } }, onError: setMutationError });
  return <div className="space-y-8"><PageHeader eyebrow="Session ownership" title="Sesiones activas" description="Cada tarjeta viene del backend y está limitada al userId autenticado. Revocar la sesión actual termina también este frontend." action={<SecondaryButton onClick={() => refetch()} disabled={isFetching}>{isFetching ? <Spinner /> : <RefreshCw className="h-4 w-4" />} Actualizar</SecondaryButton>} /><ProblemPanel error={error || mutationError} />{isLoading ? <Card className="p-8 text-sm text-slate-500">Cargando sesiones…</Card> : <div className="grid gap-4 xl:grid-cols-2">{sessions.map((session) => <SessionCard key={session.sessionId} session={session} busy={revoke.isPending} onRevoke={() => revoke.mutate(session.sessionId)} />)}{!sessions.length && <Card className="p-8 text-center"><ShieldCheck className="mx-auto h-8 w-8 text-slate-300" /><p className="mt-3 font-semibold">No hay sesiones activas</p></Card>}</div>}</div>;
}
function SessionCard({ session, onRevoke, busy }: { session: AuthSession; onRevoke: () => void; busy: boolean }) { const Icon = /mobile|android|iphone/i.test(session.userAgent || '') ? Smartphone : Laptop; return <Card className="p-5 sm:p-6"><div className="flex items-start gap-4"><div className="grid h-11 w-11 shrink-0 place-items-center rounded-xl bg-blue-50 text-blue-600 dark:bg-blue-500/10 dark:text-blue-300"><Icon className="h-5 w-5" /></div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><p className="truncate font-semibold">{friendlyAgent(session.userAgent)}</p>{session.current && <StatusPill tone="blue">sesión actual</StatusPill>}</div><p className="mt-1 truncate text-xs text-slate-500" title={session.userAgent || ''}>{session.userAgent || 'User-Agent no disponible'}</p></div></div><dl className="mt-5 grid gap-3 sm:grid-cols-2"><Detail label="IP" value={session.ipAddress || '—'} /><Detail label="Session ID" value={session.sessionId} /><Detail label="Creada" value={formatDate(session.createdAt)} /><Detail label="Último uso" value={formatDate(session.lastUsedAt)} /><Detail label="Expira" value={formatDate(session.expiresAt)} /></dl><div className="mt-5 flex justify-end"><DangerButton onClick={onRevoke} disabled={busy}><Trash2 className="h-4 w-4" /> {session.current ? 'Revocar y salir' : 'Revocar sesión'}</DangerButton></div></Card>; }
function friendlyAgent(agent: string | null) { if (!agent) return 'Cliente desconocido'; if (/chrome/i.test(agent)) return 'Chrome / Chromium'; if (/firefox/i.test(agent)) return 'Firefox'; if (/safari/i.test(agent)) return 'Safari'; return 'Cliente autenticado'; }

export function TokensPage() {
  const auth = useAuth(); const now = useNow(); const [refreshing, setRefreshing] = useState(false); const accessTtl = secondsUntil(auth.tokens?.accessTokenExpiresAt, now); const refreshTtl = secondsUntil(auth.tokens?.refreshTokenExpiresAt, now);
  async function rotate() { setRefreshing(true); try { const ok = await auth.refresh(); ok ? toast.success('Refresh rotado') : toast.error('Refresh rechazado'); } finally { setRefreshing(false); } }
  return <div className="space-y-8"><PageHeader eyebrow="JWT inspection" title="Tokens y claims" description="Decodificación local para observar el contrato. El navegador no verifica la firma: la autoridad sigue siendo el backend." action={<Button onClick={rotate} disabled={refreshing}>{refreshing ? <Spinner /> : <RefreshCw className="h-4 w-4" />} Rotar refresh</Button>} /><div className="grid gap-4 sm:grid-cols-2"><Card className="p-5"><p className="text-xs font-bold uppercase tracking-[.16em] text-slate-400">Access token</p><p className="font-display mt-3 text-2xl font-bold">{duration(accessTtl)}</p><p className="mt-1 text-xs text-slate-500">Expira {auth.tokens?.accessTokenExpiresAt ? formatDate(auth.tokens.accessTokenExpiresAt) : '—'}</p></Card><Card className="p-5"><p className="text-xs font-bold uppercase tracking-[.16em] text-slate-400">Refresh token</p><p className="font-display mt-3 text-2xl font-bold">{duration(refreshTtl)}</p><p className="mt-1 text-xs text-slate-500">Expira {auth.tokens?.refreshTokenExpiresAt ? formatDate(auth.tokens.refreshTokenExpiresAt) : '—'}</p></Card></div><TokenBlock title="Access token" token={auth.tokens?.accessToken || ''} /><div className="grid gap-6 xl:grid-cols-2"><JsonCard title="JOSE header" value={auth.jwt.header} icon={<Fingerprint className="h-5 w-5" />} /><JsonCard title="JWT claims" value={auth.jwt.claims} icon={<KeyRound className="h-5 w-5" />} /></div><Card className="p-5"><p className="font-semibold">Refresh token</p><p className="mt-2 text-sm text-slate-500 dark:text-slate-400">Se muestra enmascarado a propósito. AuthLab necesita su valor para probar la rotación, pero nunca lo escribe en el activity log.</p><code className="mt-4 block break-all rounded-xl bg-slate-950 p-4 text-xs text-slate-300">{mask(auth.tokens?.refreshToken || '')}</code></Card></div>;
}
function TokenBlock({ title, token }: { title: string; token: string }) { async function copy() { await navigator.clipboard.writeText(token); toast.success('Token copiado'); } return <Card className="p-5"><div className="flex items-center justify-between"><p className="font-semibold">{title}</p><SecondaryButton onClick={copy}><Copy className="h-4 w-4" /> Copiar</SecondaryButton></div><code className="mt-4 block max-h-32 overflow-auto break-all rounded-xl bg-slate-950 p-4 text-xs leading-5 text-slate-300 scrollbar-thin">{token}</code></Card>; }
function JsonCard({ title, value, icon }: { title: string; value: unknown; icon: ReactNode }) { return <Card className="overflow-hidden"><div className="flex items-center gap-3 border-b border-slate-200 px-5 py-4 dark:border-slate-800"><span className="text-[#0055FF]">{icon}</span><p className="font-semibold">{title}</p></div><pre className="max-h-[420px] overflow-auto p-5 text-xs leading-6 text-slate-600 scrollbar-thin dark:text-slate-300">{JSON.stringify(value, null, 2)}</pre></Card>; }
function mask(value: string) { if (value.length <= 16) return '••••••••'; return `${value.slice(0, 8)}${'•'.repeat(28)}${value.slice(-8)}`; }

export function RecoveryPage() {
  const [email, setEmail] = useState(''); const [verifyError, setVerifyError] = useState<unknown>(null); const [resetError, setResetError] = useState<unknown>(null); const [verifyOk, setVerifyOk] = useState(false); const [resetOk, setResetOk] = useState(false); const [verifyBusy, setVerifyBusy] = useState(false); const [resetBusy, setResetBusy] = useState(false);
  async function resendVerification() { setVerifyBusy(true); setVerifyError(null); setVerifyOk(false); try { await authApi.resendVerification(email); setVerifyOk(true); } catch (error) { setVerifyError(error); } finally { setVerifyBusy(false); } }
  async function reset() { setResetBusy(true); setResetError(null); setResetOk(false); try { await authApi.requestPasswordReset(email); setResetOk(true); } catch (error) { setResetError(error); } finally { setResetBusy(false); } }
  return <div className="space-y-8"><PageHeader eyebrow="Recovery surface" title="Verificación y recuperación" description="Prueba los endpoints públicos con respuesta genérica y observa el rate limit por cuenta/IP sin automatizar una ráfaga de requests." /><Card className="max-w-2xl p-5 sm:p-6"><Field label="Correo a probar" type="email" value={email} onChange={(e) => setEmail(e.target.value)} placeholder="cuenta@ejemplo.com" /><p className="mt-3 text-xs leading-5 text-slate-500">Puedes usar una cuenta real o inexistente. La respuesta pública debería mantener la misma semántica 202 mientras el rate limit no se exceda.</p></Card><div className="grid gap-6 xl:grid-cols-2"><RecoveryCard title="Reenviar verificación" text="POST /email-verification" busy={verifyBusy} disabled={!email} onClick={resendVerification} success={verifyOk} error={verifyError} /><RecoveryCard title="Solicitar password reset" text="POST /password-reset" busy={resetBusy} disabled={!email} onClick={reset} success={resetOk} error={resetError} /></div><Card className="border-amber-200 bg-amber-50 p-5 dark:border-amber-900/40 dark:bg-amber-950/20"><div className="flex gap-3"><AlertTriangle className="mt-0.5 h-5 w-5 shrink-0 text-amber-600" /><div><p className="font-semibold">Rate limit manual</p><p className="mt-1 text-sm leading-6 text-amber-900/75 dark:text-amber-200/80">Repite una acción manualmente si quieres llegar al 429. AuthLab mostrará <code>Retry-After</code>. No incluye un botón de “bombardear” el endpoint para evitar generar carga accidental.</p></div></div></Card></div>;
}
function RecoveryCard({ title, text, busy, disabled, onClick, success, error }: { title: string; text: string; busy: boolean; disabled: boolean; onClick: () => void; success: boolean; error: unknown }) { return <Card className="p-5 sm:p-6"><RotateCcwKey className="h-6 w-6 text-[#0055FF]" /><h2 className="font-display mt-4 text-xl font-bold">{title}</h2><p className="mt-1 font-mono text-xs text-slate-400">{text}</p><p className="mt-4 text-sm leading-6 text-slate-500 dark:text-slate-400">Una pulsación equivale a una solicitud real. Útil para validar respuestas genéricas, 429 y fallos 503 si Redis no está disponible.</p><Button className="mt-5" onClick={onClick} disabled={disabled || busy}>{busy ? <Spinner /> : <Server className="h-4 w-4" />} Ejecutar solicitud</Button>{success && <div className="mt-4"><SuccessPanel>202 Accepted. No se infiere si la cuenta existe.</SuccessPanel></div>}<div className="mt-4"><ProblemPanel error={error} /></div></Card>; }

export function SecurityLabPage() {
  const auth = useAuth(); const queryClient = useQueryClient(); const navigate = useNavigate(); const [sessionId, setSessionId] = useState(() => crypto.randomUUID()); const [idorError, setIdorError] = useState<unknown>(null); const [idorResult, setIdorResult] = useState<string | null>(null); const [idorBusy, setIdorBusy] = useState(false); const [revocationBusy, setRevocationBusy] = useState(false); const [revocationSteps, setRevocationSteps] = useState<Array<{ label: string; ok: boolean; detail: string }>>([]);
  async function probeIdor(event: FormEvent) { event.preventDefault(); setIdorBusy(true); setIdorError(null); setIdorResult(null); try { await apiRequest<null>(`/api/v1/auth/sessions/${encodeURIComponent(sessionId)}`, { method: 'DELETE', auth: true, retryAuth: false }); setIdorResult('El backend aceptó la revocación. Si la UUID era ajena, investiga inmediatamente.'); queryClient.invalidateQueries({ queryKey: ['sessions'] }); } catch (error) { setIdorError(error); if (error instanceof ApiError && [403, 404].includes(error.status)) setIdorResult('Ownership protegido: la UUID no produjo una revocación transversal.'); } finally { setIdorBusy(false); } }
  async function demonstrateRevocation() { if (!auth.tokens) return; const snapshot = auth.tokens; setRevocationBusy(true); setRevocationSteps([]); const steps: Array<{ label: string; ok: boolean; detail: string }> = []; try { await apiRequest<null>('/api/v1/auth/logout', { method: 'POST', auth: true, retryAuth: false }); steps.push({ label: '1. Revocar sesión actual', ok: true, detail: 'POST /logout → 204' }); setRevocationSteps([...steps]); try { await apiRequest<AuthSession[]>('/api/v1/auth/sessions', { auth: true, retryAuth: false }); steps.push({ label: '2. Reutilizar access JWT', ok: true, detail: 'El access token siguió siendo criptográficamente válido, comportamiento stateless esperado hasta exp.' }); } catch (error) { steps.push({ label: '2. Reutilizar access JWT', ok: false, detail: describeError(error) }); } setRevocationSteps([...steps]); try { await authApi.refresh(snapshot.refreshToken); steps.push({ label: '3. Reutilizar refresh token', ok: false, detail: 'El refresh fue aceptado inesperadamente.' }); } catch (error) { steps.push({ label: '3. Reutilizar refresh token', ok: true, detail: `Refresh rechazado: ${describeError(error)}` }); } setRevocationSteps([...steps]); } finally { setRevocationBusy(false); } }
  return <div className="space-y-8"><PageHeader eyebrow="Controlled destructive tests" title="Security Lab" description="Pruebas manuales de contrato y seguridad. Nada corre en bucle y ninguna acción intenta explotar servicios externos." /><div className="grid gap-6 xl:grid-cols-2"><Card className="p-5 sm:p-6"><FlaskConical className="h-6 w-6 text-violet-600" /><h2 className="font-display mt-4 text-xl font-bold">Probe de ownership / IDOR</h2><p className="mt-2 text-sm leading-6 text-slate-500 dark:text-slate-400">Envía un DELETE con una UUID elegida manualmente. Una sesión inexistente o que no pertenece al usuario no debería permitir controlar sesiones de terceros.</p><form className="mt-5 space-y-4" onSubmit={probeIdor}><Field label="Session UUID" value={sessionId} onChange={(e) => setSessionId(e.target.value)} required /><Button disabled={idorBusy}>{idorBusy ? <Spinner /> : <Fingerprint className="h-4 w-4" />} Probar UUID</Button></form>{idorResult && <p className="mt-4 rounded-xl bg-slate-50 p-3 text-sm dark:bg-slate-900">{idorResult}</p>}<div className="mt-4"><ProblemPanel error={idorError} /></div></Card><Card className="border-rose-200 p-5 sm:p-6 dark:border-rose-900/50"><LogOut className="h-6 w-6 text-rose-600" /><h2 className="font-display mt-4 text-xl font-bold">Demostración de revocación stateless</h2><p className="mt-2 text-sm leading-6 text-slate-500 dark:text-slate-400">Revoca <strong>tu sesión actual</strong>, intenta usar el access JWT una vez más y luego prueba el refresh revocado. AuthLab conserva temporalmente el access token para enseñarte el resultado.</p><div className="mt-4 rounded-xl border border-rose-200 bg-rose-50 p-3 text-xs leading-5 text-rose-900 dark:border-rose-900/60 dark:bg-rose-950/20 dark:text-rose-200">Esta prueba cierra tu sesión persistida. Está diseñada para demostrar el tradeoff intencional: access JWT stateless hasta expiración, refresh/session revocados inmediatamente.</div><DangerButton className="mt-5" onClick={demonstrateRevocation} disabled={revocationBusy}>{revocationBusy ? <Spinner /> : <AlertTriangle className="h-4 w-4" />} Revocar y ejecutar prueba</DangerButton>{revocationSteps.length > 0 && <div className="mt-5 space-y-2">{revocationSteps.map((step) => <div key={step.label} className="rounded-xl bg-slate-50 p-3 dark:bg-slate-900"><div className="flex gap-2"><span className={step.ok ? 'text-emerald-600' : 'text-rose-600'}>{step.ok ? '✓' : '×'}</span><p className="font-semibold text-sm">{step.label}</p></div><p className="mt-1 pl-5 text-xs leading-5 text-slate-500">{step.detail}</p></div>)}</div>}{revocationSteps.length >= 3 && !revocationBusy && <Button className="mt-4" onClick={() => { auth.clear(); navigate('/login', { replace: true }); }}>Finalizar laboratorio e iniciar sesión</Button>}</Card></div></div>;
}
function describeError(error: unknown) { if (error instanceof ApiError) return `HTTP ${error.status}${error.problem?.code ? ` · ${error.problem.code}` : ''}`; return error instanceof Error ? error.message : 'error desconocido'; }

export function ActivityPage() {
  const entries = useSyncExternalStore(activityStore.subscribe, activityStore.getSnapshot, activityStore.getSnapshot);
  return <div className="space-y-8"><PageHeader eyebrow="Client telemetry" title="Actividad API" description="Historial efímero del navegador. Registra ruta, status, latencia y código Problem Details; nunca body, contraseña ni token." action={<SecondaryButton onClick={() => activityStore.clear()}><Trash2 className="h-4 w-4" /> Limpiar</SecondaryButton>} /><Card className="overflow-hidden"><div className="overflow-x-auto scrollbar-thin"><table className="w-full min-w-[780px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-[.12em] text-slate-400 dark:bg-slate-900"><tr><th className="px-5 py-3">Hora</th><th className="px-5 py-3">Request</th><th className="px-5 py-3">Status</th><th className="px-5 py-3">Duración</th><th className="px-5 py-3">Problem code</th><th className="px-5 py-3">Retry-After</th></tr></thead><tbody className="divide-y divide-slate-200 dark:divide-slate-800">{entries.map((entry) => <ActivityRow key={entry.id} entry={entry} />)}{!entries.length && <tr><td colSpan={6} className="px-5 py-12 text-center text-slate-500"><Activity className="mx-auto h-7 w-7 text-slate-300" /><p className="mt-3">Aún no hay llamadas en esta sesión del navegador.</p></td></tr>}</tbody></table></div></Card><p className="text-xs text-slate-400">Base URL actual: <span className="font-mono">{API_BASE_URL}</span>. El historial se borra al recargar y conserva como máximo 80 entradas.</p></div>;
}
function ActivityRow({ entry }: { entry: ActivityEntry }) { return <tr><td className="whitespace-nowrap px-5 py-4 text-xs text-slate-500">{new Date(entry.at).toLocaleTimeString('es-MX')}</td><td className="px-5 py-4"><span className="mr-2 rounded bg-slate-100 px-2 py-1 font-mono text-[10px] font-bold dark:bg-slate-800">{entry.method}</span><span className="font-mono text-xs">{entry.path}</span></td><td className="px-5 py-4"><StatusPill tone={entry.status < 300 ? 'green' : entry.status === 429 ? 'amber' : 'rose'}>{entry.status}</StatusPill></td><td className="px-5 py-4 text-xs">{entry.durationMs} ms</td><td className="px-5 py-4 font-mono text-xs text-slate-500">{entry.problemCode || '—'}</td><td className="px-5 py-4 text-xs text-slate-500">{entry.retryAfter ? `${entry.retryAfter}s` : '—'}</td></tr>; }
