import type { PropsWithChildren, ReactNode } from 'react';
import { Link } from 'react-router-dom';
import { CheckCircle2, KeyRound, ShieldCheck, TimerReset } from 'lucide-react';
import { API_BASE_URL } from '../lib/api';

export function AuthShell({ children, title, description, asideTitle = 'Prueba el flujo completo, no solo el happy path.' }: PropsWithChildren<{ title: ReactNode; description: ReactNode; asideTitle?: string }>) {
  return <div className="grid min-h-screen bg-white lg:grid-cols-[minmax(0,1.05fr)_minmax(460px,.95fr)] dark:bg-slate-950"><main className="flex min-h-screen items-center justify-center px-5 py-12 sm:px-8"><div className="w-full max-w-[460px]"><Link to="/login" className="focus-ring inline-flex items-center gap-3 rounded-xl"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#0055FF] text-white"><ShieldCheck className="h-5 w-5" /></span><span><span className="font-display block text-lg font-bold text-slate-950 dark:text-white">AuthLab</span><span className="block text-[10px] font-bold uppercase tracking-[.17em] text-slate-400">Authentication test console</span></span></Link><div className="mt-10"><h1 className="font-display text-3xl font-bold tracking-tight text-slate-950 sm:text-4xl dark:text-white">{title}</h1><p className="mt-3 text-sm leading-6 text-slate-500 sm:text-base dark:text-slate-400">{description}</p></div><div className="mt-8">{children}</div><p className="mt-7 text-center text-xs text-slate-400">API: <span className="font-mono">{API_BASE_URL}</span></p></div></main><aside className="relative hidden overflow-hidden bg-slate-950 p-10 text-white lg:flex lg:flex-col lg:justify-between"><div className="absolute inset-0 grid-fade opacity-70" /><div className="absolute -right-28 top-16 h-72 w-72 rounded-full bg-blue-600/30 blur-3xl" /><div className="absolute -bottom-24 left-10 h-72 w-72 rounded-full bg-violet-600/20 blur-3xl" /><div className="relative z-10 max-w-xl"><p className="text-xs font-bold uppercase tracking-[.2em] text-blue-300">Backend validation surface</p><h2 className="font-display mt-4 text-4xl font-semibold leading-tight">{asideTitle}</h2><p className="mt-5 max-w-lg text-sm leading-7 text-slate-300">El frontend está hecho como consola de aceptación: conserva el lenguaje visual de EleVideo, pero cada tarjeta tiene una razón técnica detrás.</p></div><div className="relative z-10 grid gap-3 sm:grid-cols-2"><Feature icon={KeyRound} title="JWT + refresh" text="Rotación, expiración y claims visibles." /><Feature icon={TimerReset} title="Recovery" text="Verificación y reset usando los links reales." /><Feature icon={ShieldCheck} title="Sesiones" text="Listar y revocar sesiones del usuario." /><Feature icon={CheckCircle2} title="RFC 9457" text="Errores y Retry-After tal como llegan." /></div></aside></div>;
}

function Feature({ icon: Icon, title, text }: { icon: typeof ShieldCheck; title: string; text: string }) {
  return <div className="rounded-2xl border border-white/10 bg-white/[.06] p-4 backdrop-blur-sm"><Icon className="h-5 w-5 text-blue-300" /><p className="mt-3 font-semibold">{title}</p><p className="mt-1 text-xs leading-5 text-slate-400">{text}</p></div>;
}
